FROM docker.elastic.co/elasticsearch/elasticsearch:8.8.1

# RUN elasticsearch-plugin install https://github.com/WorksApplications/elasticsearch-sudachi/releases/download/v3.1.0/elasticsearch-8.8.1-analysis-sudachi-3.1.0.zip
